kind: pipeline
name: default

steps:
- name: build
  image: maven:3.6.0-jdk-11-slim
  commands:
  - mvn install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  
- name: test
  image: maven:3.6.0-jdk-11-slim
  commands:
  - mvn clean test -B
  
- name: deploy
  image: maven:3.6.0-jdk-11-slim
  commands:
  - echo "$SERVICE_ACCOUNT" > $GOOGLE_APPLICATION_CREDENTIALS
  - mvn deploy:deploy -B -DskipTests
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: /sa
    SERVICE_ACCOUNT:
      from_secret: service_account
  when:
    branch:
    - master
    - develop
